import Link from "next/link";
import { ArrowRight, BadgeCheck, Check, Home, MapPin, MessageCircle, PackageCheck, Phone, Sparkles, Store, Truck, WalletCards } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { brand, products, type Locale, type ProductSlug, whatsappMessages, whatsappUrl } from "@/src/config/brand";
import { copy, faqItems } from "@/src/content/site";

const path = (locale: Locale, slug = "") => `/${locale}${slug ? `/${slug}` : ""}`;

export function SectionHeading({ eyebrow, title, copyText, center = false }: { eyebrow?: string; title: string; copyText?: string; center?: boolean }) {
  return <div className={`section-heading ${center ? "center" : ""}`}>{eyebrow ? <p className="eyebrow">{eyebrow}</p> : null}<h2>{title}</h2>{copyText ? <p>{copyText}</p> : null}</div>;
}

export function ProductVisual({ product, large = false }: { product: (typeof products)[number]; large?: boolean }) {
  return <div className={`product-visual product-${product.color} ${large ? "product-visual-large" : ""}`} role="img" aria-label={`Placeholder for ${product.name.en} product photography`}>
    <span className="visual-orbit orbit-one" /><span className="visual-orbit orbit-two" />
    <span className="visual-label"><small>GharChamak</small><strong>{product.variant.en}</strong><em>Product image<br />coming soon</em></span>
  </div>;
}

export function ProductCard({ product, locale }: { product: (typeof products)[number]; locale: Locale }) {
  const c = copy[locale];
  return <article className="product-card"><ProductVisual product={product} /><div className="product-card-body"><span className="status-chip">{c.common.coming}</span><p className="product-variant">{product.variant[locale]}</p><h3>{product.name[locale]}</h3><p>{product.short[locale]}</p><Link className="text-link" href={path(locale, `products/${product.slug}`)}>{c.common.learn}<ArrowRight size={17} /></Link></div></article>;
}

export function FaqList({ locale, limit }: { locale: Locale; limit?: number }) {
  const items = limit ? faqItems[locale].slice(0, limit) : faqItems[locale];
  return <Accordion className="faq-list" type="multiple">{items.map(([question, answer], i) => <AccordionItem value={`item-${i}`} key={question}><AccordionTrigger className="faq-question">{question}</AccordionTrigger><AccordionContent className="faq-answer"><p>{answer}</p></AccordionContent></AccordionItem>)}</Accordion>;
}

const benefits = {
  en: [[Sparkles, "Strong Clean", "Products should perform where it matters — in everyday use."], [WalletCards, "Fair Price", "Good household cleaning should remain accessible."], [BadgeCheck, "Consistent Quality", "Customers should know what to expect every time."], [Home, "Made for Everyday Homes", "Simple products built around real household needs."]],
  ne: [[Sparkles, "बलियो सफाइ", "दैनिक प्रयोगमा आवश्यक ठाउँमा उत्पादनले काम गर्नुपर्छ।"], [WalletCards, "सही दाम", "राम्रो घर सफाइ सबैको पहुँचमा रहनुपर्छ।"], [BadgeCheck, "एकरूप गुणस्तर", "ग्राहकले हरेक पटक के अपेक्षा गर्ने भन्ने थाहा पाउनुपर्छ।"], [Home, "दैनिक घरका लागि", "वास्तविक घरायसी आवश्यकतामा आधारित सरल उत्पादन।"]],
} as const;

export function HomePage({ locale }: { locale: Locale }) {
  const c = copy[locale];
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="brand-kicker">GharChamak <span>by Pasalho</span></p><h1><span>{locale === "en" ? "Strong Clean." : "बलियो सफाइ।"}</span><span className="hero-accent">{locale === "en" ? "Fair Price." : "सही दाम।"}</span></h1><p className="hero-ne" lang="ne">{brand.taglineNe}</p><p className="hero-description">{c.home.heroCopy}</p><div className="button-row"><Link className="btn btn-primary" href={path(locale, "products")}>{c.home.explore}<ArrowRight size={18} /></Link><a className="btn btn-secondary" href={whatsappUrl(whatsappMessages.general)} target="_blank" rel="noreferrer"><MessageCircle size={18} />{c.common.chat}</a></div><p className="trust-line"><BadgeCheck size={17} />GharChamak by Pasalho</p></div><div className="hero-products" aria-label="GharChamak product categories">{products.map((p, i) => <div className={`hero-product hero-product-${i + 1}`} key={p.slug}><ProductVisual product={p} /></div>)}</div></div></section>
    <section className="section idea-section"><div className="container split-intro"><SectionHeading eyebrow={locale === "en" ? "The GharChamak idea" : "घरचमकको विचार"} title={c.home.ideaTitle} copyText={c.home.ideaCopy} /><div className="idea-points">{(locale === "en" ? ["Effective everyday cleaning", "Consistent quality", "Fair everyday value"] : ["प्रभावकारी दैनिक सफाइ", "एकरूप गुणस्तर", "दैनिक उचित मूल्य"]).map((item, i) => <div key={item}><span>0{i + 1}</span><strong>{item}</strong></div>)}</div></div></section>
    <section className="section products-section"><div className="container"><SectionHeading eyebrow={c.nav.products} title={c.home.made} copyText={c.home.madeCopy} /><div className="product-grid">{products.map(p => <ProductCard key={p.slug} product={p} locale={locale} />)}</div></div></section>
    <section className="section principles-section"><div className="container"><SectionHeading title={c.home.stands} center /><div className="benefit-grid">{benefits[locale].map(([Icon, title, text]) => <article className="benefit-card" key={title}><span className="icon-box"><Icon size={24} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="value-section"><div className="container value-inner"><p className="value-mark" aria-hidden="true">G</p><div><p className="eyebrow">{locale === "en" ? "Our value philosophy" : "हाम्रो मूल्य सोच"}</p><h2>{c.home.valueLine}</h2><p>{c.home.valueCopy}</p></div></div></section>
    <RetailerBanner locale={locale} />
    <section className="section story-section"><div className="container story-grid"><div className="story-brand"><span className="story-g">G</span><p>GHARCHAMAK</p><small>by Pasalho</small></div><div><SectionHeading eyebrow={locale === "en" ? "Our story" : "हाम्रो कथा"} title={c.home.storyTitle} copyText={c.home.storyCopy} /><Link className="text-link" href={path(locale, "about")}>{locale === "en" ? "Read our story" : "हाम्रो कथा पढ्नुहोस्"}<ArrowRight size={17} /></Link></div></div></section>
    <section className="section faq-section"><div className="container faq-grid"><SectionHeading eyebrow="FAQ" title={locale === "en" ? "Clear answers, no guesswork." : "स्पष्ट उत्तर, कुनै अनुमान होइन।"} copyText={locale === "en" ? "The essentials about GharChamak, availability and future stocking." : "घरचमक, उपलब्धता र भविष्यको स्टकबारे मुख्य जानकारी।"} /><div><FaqList locale={locale} limit={6} /><Link className="text-link faq-more" href={path(locale, "faq")}>{locale === "en" ? "View all questions" : "सबै प्रश्न हेर्नुहोस्"}<ArrowRight size={17} /></Link></div></div></section>
    <ContactBanner locale={locale} />
  </>;
}

export function RetailerBanner({ locale }: { locale: Locale }) { const c = copy[locale]; return <section className="retailer-section"><div className="container retailer-grid"><div><p className="eyebrow light">{locale === "en" ? "For trade partners" : "व्यापार साझेदारका लागि"}</p><h2>{c.home.retailerTitle}</h2><p>{c.home.retailerCopy}</p><a className="btn btn-white" href={whatsappUrl(whatsappMessages.retailer)} target="_blank" rel="noreferrer">{c.common.enquiry}<ArrowRight size={18} /></a></div><ul>{(locale === "en" ? ["Clear product positioning", "Consumer-friendly pricing", "Professional packaging", "Reliable supply ambition", "Retailer-focused partnership"] : ["स्पष्ट उत्पादन पहिचान", "ग्राहकमैत्री मूल्य", "व्यावसायिक प्याकेजिङ", "भरपर्दो आपूर्ति लक्ष्य", "विक्रेता-केन्द्रित साझेदारी"]).map(item => <li key={item}><Check size={17} />{item}</li>)}</ul></div></section>; }

export function ContactBanner({ locale }: { locale: Locale }) { const c = copy[locale]; return <section className="contact-banner"><div className="container contact-banner-inner"><div><p className="eyebrow">WhatsApp</p><h2>{c.home.contactTitle}</h2><p>{c.home.contactCopy}</p></div><a className="btn btn-primary" href={whatsappUrl(whatsappMessages.general)} target="_blank" rel="noreferrer"><MessageCircle size={19} />{c.common.chat}</a></div></section>; }

export function PageIntro({ eyebrow, title, copyText }: { eyebrow: string; title: string; copyText: string }) { return <section className="page-intro"><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copyText}</p></div></section>; }

export function ProductsPage({ locale }: { locale: Locale }) { const c = copy[locale]; return <><PageIntro eyebrow={c.nav.products} title={c.home.made} copyText={locale === "en" ? "Three focused household cleaning products are in development. Honest information will be added as each product is finalized." : "तीनवटा केन्द्रित घर सफाइ उत्पादन विकासमा छन्। प्रत्येक उत्पादन अन्तिम भएपछि प्रमाणित जानकारी थपिनेछ।"} /><section className="section"><div className="container product-grid">{products.map(p => <ProductCard key={p.slug} product={p} locale={locale} />)}</div></section><section className="small-note"><div className="container"><PackageCheck size={24} /><div><h2>{locale === "en" ? "Launch information, kept honest." : "बजार जानकारी, स्पष्ट रूपमा।"}</h2><p>{locale === "en" ? "Prices, pack sizes, ingredients and retail availability will only be published after they are confirmed." : "मूल्य, प्याक साइज, सामग्री र खुद्रा उपलब्धता पुष्टि भएपछि मात्र प्रकाशित गरिनेछ।"}</p></div></div></section><ContactBanner locale={locale} /></>; }

export function ProductPage({ locale, slug }: { locale: Locale; slug: ProductSlug }) {
  const c = copy[locale]; const product = products.find(p => p.slug === slug)!; const related = products.filter(p => p.slug !== slug);
  const message = `Namaste, I would like more information about ${product.name.en}.`;
  return <><section className="product-hero"><div className="container"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href={path(locale)}>{c.common.home}</Link><span>/</span><Link href={path(locale, "products")}>{c.nav.products}</Link><span>/</span><span>{product.name[locale]}</span></nav><div className="product-detail-grid"><ProductVisual product={product} large /><div><span className="status-chip">{c.common.coming}</span><p className="product-variant">{product.variant[locale]}</p><h1>{product.name[locale]}</h1><p className="product-lead">{product.short[locale]}</p><a className="btn btn-primary" href={whatsappUrl(message)} target="_blank" rel="noreferrer"><MessageCircle size={18} />{c.common.productEnquiry}</a></div></div></div></section><section className="section"><div className="container detail-grid"><article><h2>{c.common.characteristics}</h2><ul className="check-list">{product.characteristics[locale].map(item => <li key={item}><Check size={18} />{item}</li>)}</ul></article><article><h2>{c.common.use}</h2><p>{product.use[locale]}</p></article><article><h2>{c.common.packSizes}</h2><p>{c.common.packPending}</p></article><article><h2>{c.common.safety}</h2><p>{c.common.safetyCopy}</p></article></div></section><section className="section related-section"><div className="container"><SectionHeading title={c.common.related} /><div className="product-grid related-grid">{related.map(p => <ProductCard key={p.slug} product={p} locale={locale} />)}</div></div></section></>;
}

export function WhyPage({ locale }: { locale: Locale }) { const c = copy[locale]; return <><PageIntro eyebrow={c.nav.why} title={locale === "en" ? "Dependable cleaning. Sensible value." : "भरपर्दो सफाइ। उचित मूल्य।"} copyText={locale === "en" ? "GharChamak is being built for the practical middle: trustworthy everyday performance without unnecessary premium pricing." : "घरचमक व्यावहारिक बीचको विकल्पका रूपमा बन्दैछ: अनावश्यक महँगो मूल्यबिना भरपर्दो दैनिक सफाइ।"} /><section className="section"><div className="container benefit-grid">{benefits[locale].map(([Icon, title, text]) => <article className="benefit-card elevated" key={title}><span className="icon-box"><Icon size={24} /></span><h2>{title}</h2><p>{text}</p></article>)}</div></section><section className="value-section"><div className="container value-inner"><p className="value-mark">G</p><div><h2>{c.home.valueLine}</h2><p>{c.home.valueCopy}</p></div></div></section><ContactBanner locale={locale} /></>; }

export function RetailersPage({ locale }: { locale: Locale }) { const c = copy[locale]; return <><PageIntro eyebrow={c.nav.retailers} title={locale === "en" ? "A practical brand for practical shelves." : "व्यावहारिक पसलका लागि व्यावहारिक ब्रान्ड।"} copyText={locale === "en" ? "Retailers, wholesalers and distribution partners can register interest in GharChamak’s planned product range." : "खुद्रा विक्रेता, थोक विक्रेता र वितरण साझेदारले घरचमकको योजनाबद्ध उत्पादन दायरामा रुचि दर्ता गर्न सक्छन्।"} /><section className="section"><div className="container trade-grid"><article><Store size={28} /><h2>{locale === "en" ? "Retailers" : "खुद्रा विक्रेता"}</h2><p>{locale === "en" ? "Tell us about your store and the customers you serve. We’ll share confirmed stocking information when it is ready." : "आफ्नो पसल र ग्राहकबारे बताउनुहोस्। पुष्टि भएको स्टक जानकारी तयार भएपछि हामी साझा गर्नेछौं।"}</p><a className="text-link" href={whatsappUrl(whatsappMessages.retailer)} target="_blank" rel="noreferrer">{c.common.enquiry}<ArrowRight size={17} /></a></article><article><Truck size={28} /><h2>{locale === "en" ? "Distributors & wholesalers" : "वितरक र थोक विक्रेता"}</h2><p>{locale === "en" ? "Share your coverage area and distribution interest directly with the GharChamak team." : "आफ्नो वितरण क्षेत्र र सहकार्यको रुचि घरचमक टोलीसँग सिधै साझा गर्नुहोस्।"}</p><a className="text-link" href={whatsappUrl(whatsappMessages.distributor)} target="_blank" rel="noreferrer">{locale === "en" ? "Distributor enquiry" : "वितरण सोधपुछ"}<ArrowRight size={17} /></a></article></div></section><RetailerBanner locale={locale} /></>; }

export function AboutPage({ locale }: { locale: Locale }) { const c = copy[locale]; return <><PageIntro eyebrow={c.nav.about} title={locale === "en" ? "A home-care brand by Pasalho." : "पसल्होको होम-केयर ब्रान्ड।"} copyText={c.home.storyCopy} /><section className="section"><div className="container about-grid"><article><p className="eyebrow">{locale === "en" ? "Our mission" : "हाम्रो उद्देश्य"}</p><h2>{locale === "en" ? "Make dependable everyday cleaning accessible to more Nepali households." : "भरपर्दो दैनिक सफाइ धेरै नेपाली घरको पहुँचमा पुर्‍याउनु।"}</h2></article><article><h2>{locale === "en" ? "Why GharChamak exists" : "घरचमक किन बनिरहेको छ"}</h2><p>{locale === "en" ? "Families should not have to choose between questionable quality and unnecessary premium pricing. We believe clear products, consistent quality and sensible prices can earn trust over time." : "परिवारले शंकास्पद गुणस्तर र अनावश्यक महँगो मूल्यबीच छनोट गर्न नपरोस्। स्पष्ट उत्पादन, एकरूप गुणस्तर र उचित मूल्यले समयसँगै विश्वास जित्न सक्छ भन्ने हाम्रो विश्वास हो।"}</p><blockquote><strong>{brand.tagline}</strong><span lang="ne">{brand.taglineNe}</span></blockquote></article></div></section><ContactBanner locale={locale} /></>; }

export function FaqPage({ locale }: { locale: Locale }) { return <><PageIntro eyebrow="FAQ" title={locale === "en" ? "Questions about GharChamak" : "घरचमकबारे प्रश्नहरू"} copyText={locale === "en" ? "Direct, factual answers about the brand, products, launch and trade enquiries." : "ब्रान्ड, उत्पादन, बजार प्रवेश र व्यापारिक सोधपुछबारे सीधा र तथ्यपरक उत्तर।"} /><section className="section"><div className="container narrow"><FaqList locale={locale} /></div></section><ContactBanner locale={locale} /></>; }

export function ContactPage({ locale }: { locale: Locale }) { const c = copy[locale]; return <><PageIntro eyebrow={c.nav.contact} title={c.home.contactTitle} copyText={c.home.contactCopy} /><section className="section"><div className="container contact-grid"><article className="contact-primary"><MessageCircle size={32} /><h2>WhatsApp</h2><p>{locale === "en" ? "For product questions, launch updates and general enquiries." : "उत्पादन प्रश्न, बजार अपडेट र सामान्य सोधपुछका लागि।"}</p><a className="btn btn-primary" href={whatsappUrl(whatsappMessages.general)} target="_blank" rel="noreferrer">{brand.phoneDisplay}</a></article><article><Phone size={26} /><h2>{locale === "en" ? "Phone" : "फोन"}</h2><a href={`tel:${brand.phone}`}>{brand.phoneDisplay}</a></article><article><MapPin size={26} /><h2>{locale === "en" ? "Location" : "स्थान"}</h2><p>{c.common.location}</p><small>{locale === "en" ? "No public street address is listed." : "सार्वजनिक सडक ठेगाना सूचीबद्ध गरिएको छैन।"}</small></article><article><Store size={26} /><h2>{locale === "en" ? "Trade enquiries" : "व्यापारिक सोधपुछ"}</h2><a href={whatsappUrl(whatsappMessages.retailer)} target="_blank" rel="noreferrer">{c.common.enquiry}<ArrowRight size={16} /></a></article></div></section></>; }

export function PrivacyPage({ locale }: { locale: Locale }) { return <><PageIntro eyebrow={locale === "en" ? "Privacy" : "गोपनीयता"} title={locale === "en" ? "A simple privacy approach." : "सरल गोपनीयता दृष्टिकोण।"} copyText={locale === "en" ? "GharChamak keeps this website intentionally simple and does not collect unnecessary personal information." : "घरचमकले यो वेबसाइट सरल राख्छ र अनावश्यक व्यक्तिगत जानकारी सङ्कलन गर्दैन।"} /><section className="section"><div className="container prose"><h2>{locale === "en" ? "Information you choose to share" : "तपाईंले साझा गर्ने जानकारी"}</h2><p>{locale === "en" ? "If you contact GharChamak through WhatsApp, phone or a configured social channel, that service handles the information you send under its own privacy terms. We use your message only to respond to your enquiry and manage relevant business communication." : "WhatsApp, फोन वा उपलब्ध सामाजिक माध्यमबाट सम्पर्क गर्दा सो सेवाको गोपनीयता नियम लागू हुन्छ। तपाईंको सन्देश सोधपुछको जवाफ र सम्बन्धित व्यापारिक सम्पर्कका लागि मात्र प्रयोग हुन्छ।"}</p><h2>{locale === "en" ? "Analytics" : "एनालिटिक्स"}</h2><p>{locale === "en" ? "Analytics and advertising pixels are disabled unless valid environment IDs are configured. If enabled later, this notice should be updated before public use." : "मान्य वातावरण ID कन्फिगर नभएसम्म एनालिटिक्स र विज्ञापन पिक्सेल निष्क्रिय छन्। भविष्यमा सक्रिय गरिएमा सार्वजनिक प्रयोगअघि यो सूचना अद्यावधिक गरिनेछ।"}</p><h2>{locale === "en" ? "Contact" : "सम्पर्क"}</h2><p>{locale === "en" ? `Questions can be sent by WhatsApp or phone to ${brand.phoneDisplay}.` : `प्रश्न WhatsApp वा फोनबाट ${brand.phoneDisplay} मा पठाउन सकिन्छ।`}</p></div></section></>; }
